# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-colDidczoZNE3wMtaLa1iBwUy-Xgiq
"""

from sklearn import svm                                                                  
import numpy as np                                                                  
from sklearn.preprocessing import MaxAbsScaler                                                                  
from sklearn.model_selection import GridSearchCV                                                                  
from sklearn.preprocessing import MinMaxScaler                                                                  
from sklearn.preprocessing import StandardScaler                                                                  
                                                                  
train_x_location = "x_train_5.csv"                                                                  
train_y_location = "y_train_5.csv"                                                                  
                                                                  
test_x_location = "x_test.csv"                                                                                        
test_y_location = "y_test.csv"                                                                  
                                                                  
print("Reading training data")                                                                  
x_train = np.loadtxt(train_x_location, delimiter=",")                                                                  
y_train = np.loadtxt(train_y_location, delimiter=",")                                                                  
                                                                  
m, n = x_train.shape                                                                                                                                    
m_labels,  = y_train.shape                                                                   
l_min = y_train.min()                                                                  
                                                                  
assert m_labels == m                                                                 
assert l_min == 0                                                            
k = y_train.max()+1                                                                  
                                                                  
print(m, "examples,", n, "features,", k, "categories.")                                                                  
                                                                  
print("Reading testing data")                                                                  
x_test = np.loadtxt(test_x_location, delimiter=",")                                                                  
y_test = np.loadtxt(test_y_location, delimiter=",")                                                                  
                                                                  
m_test, n_test = x_test.shape                                                                  
m_test_labels,  = y_test.shape                                                                  
                                                                  
assert m_test_labels == m_test                                                                  
assert n_test == n                                                                  
print(m_test, "test examples.")                                                                  
                                                                  
                                                                  
print("Pre processing data")                                                                  
s=MaxAbsScaler()                                                                  
f_zero=s.fit_transform(x_train)     
# s.scale = 1                                                                      
#sc2=MinMaxScaler()                                                                                                         
# s.min = 0                                                                                                                                             
                                                                                                         
#f_zero=s.fit_transform(x_train)                                                                                                         
# s.scale = 1                                                              
f_one=s.transform(x_test)                                                                  
                                                                  
                                                                  
print("---train")                                                                  
                                                                                        
                                                                                        
param_grid = {'C': [0.1,1.0,10.0,100.0,200.0,150.0,1000.0],                                                                  
              'kernel': ['rbf'],                                                                  
              'gamma': [0.1,10] ,                                                                  
              }                                                                  
              #     print(key, value)                                                                               
# # for i in range(C):                                                                  
                                                                  
# print(a1['C'])                                                                                 
                                                              
                                                                                        
grid_search = GridSearchCV(estimator=svm.SVC(),                                                                  
                           param_grid=param_grid)                                                                  
# a1.pop('gamma')                                                                                                     
# print(a1)                                                                    
grid_search.fit(f_zero, y_train)                                                                                                                                    
#for i in range(f_zer):                                                                                                     
    #print("ite:", i)                                                                    
                                                                                                                                    
model = svm.SVC(**grid_search.best_params_)     
#for i in range(f_zer):                                                                               
    #print("ite:", i)                                                              
model.fit(f_zero, y_train)                                                                  
                                                                  
                                                                  
print("---evaluate")                                                                                                                                    
print(" number of support vectors: ", model.n_support_)                                                                  
acc = model.score(f_one, y_test)                                                                  
print("acc:", acc)